#!/bin/bash
source grade_utils
printf "\n\n### Gimatriya Part A ###\n"
make clean

i=0
printf "\n\n### Check $i: our demo program should compile with your class\n"
grade_command make -f Makefile demo
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: our demo program should run without errors\n"
grade_command ./demo
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: our test program should compile with your function\n"
grade_command make -f Makefile our_test
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

# let "i=i+1"
# printf "\n\n### Check $i: our test program should run (may have errors)\n"
# grade_command ./our_test
# grades[$i]=$grade
# printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: your test should compile \n"
grade_command make -f Makefile your_test
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

let "i=i+1"
printf "\n\n### Check $i: you should have at least 20 new tests\n"
grade_program your_test
grades[$i]=$grade
printf "### Grade $i: ${grades[$i]}\n"

# from https://stackoverflow.com/a/31653407/827927
IFS='+' average_grade=$(echo "scale=1;(${grades[*]})/${#grades[@]}"|bc)
printf "\n\nGrade: $average_grade\n\n"

make --silent clean
